server:
  port: 1001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: component-process-service-id
          uri: lb://component-process-service
          predicates:
            - Path=/returns/**
          filters:
            - name: CircuitBreaker
              args:
                name: component-process-service-id
                fallbackuri: forward:/returnFallback

        - id: payment-service-id
          uri: lb://payment-service
          predicates:
            - Path=/payments/**

        - id: packaging-delivery-service-id
          uri: lb://packaging-and-delivery-service
          predicates:
            - Path= /packagingAndDelivery/**

        - id: authentication-service-id
          uri: lb://authentication-service
          predicates:
            - Path= /auth/**

management:
  endpoints:
    web:
      exposure:
        exclude: hystrix.stream

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000


